// Column definitions shared by the Students Excel export, import template, and
// import parser — keeping the headers in exact sync so a re-exported/edited
// file always imports back cleanly.

export const STUDENT_IMPORT_COLUMNS = [
  { header: "Register Number", key: "admissionNo", required: true },
  { header: "Name", key: "name", required: true },
  { header: "Standard", key: "standardName", required: true },
  { header: "Academic Year", key: "academicYear", required: true },
  { header: "Father's Name", key: "fatherName" },
  { header: "Mother's Name", key: "motherName" },
  { header: "Gender", key: "gender" },
  { header: "Date of Birth (YYYY-MM-DD)", key: "dob" },
  { header: "Birth Place", key: "birthPlace" },
  { header: "Aadhar Number", key: "aadharNumber" },
  { header: "PEN ID", key: "penId" },
  { header: "APAAR ID", key: "apaarId" },
  { header: "Phone", key: "phone" },
  { header: "Address", key: "address" },
  { header: "District", key: "district" },
  { header: "Taluka", key: "taluka" },
  { header: "Village", key: "village" },
  { header: "Mother Tongue", key: "motherTongue" },
  { header: "Religion", key: "religion" },
  { header: "Caste", key: "caste" },
  { header: "Sub Caste", key: "subCaste" },
  { header: "Medium", key: "medium" },
  { header: "Board", key: "board" },
  { header: "School Bus (Yes/No)", key: "schoolBus" },
  { header: "Admission Date (YYYY-MM-DD)", key: "admissionDate" },
  { header: "Status (ACTIVE/INACTIVE)", key: "status" },
  { header: "School Fees (blank = auto from fee structure)", key: "customFee" },
  { header: "Discount", key: "discount" },
] as const;

export const STUDENT_EXPORT_ONLY_COLUMNS = [
  { header: "Total Fee", key: "totalFee" },
  { header: "Total Paid", key: "totalPaid" },
  { header: "Pending Fees", key: "pendingFees" },
  { header: "Advance", key: "advance" },
] as const;

export const STUDENT_TEMPLATE_SAMPLE_ROW: Record<string, string> = {
  "Register Number": "1001",
  Name: "Sample Student",
  Standard: "1st",
  "Academic Year": "2026-27",
  "Father's Name": "Sample Father",
  "Mother's Name": "Sample Mother",
  Gender: "Male",
  "Date of Birth (YYYY-MM-DD)": "2015-06-15",
  "Birth Place": "",
  "Aadhar Number": "",
  "PEN ID": "",
  "APAAR ID": "",
  Phone: "9876543210",
  Address: "",
  District: "",
  Taluka: "",
  Village: "",
  "Mother Tongue": "",
  Religion: "",
  Caste: "",
  "Sub Caste": "",
  Medium: "",
  Board: "Maharashtra State Board",
  "School Bus (Yes/No)": "No",
  "Admission Date (YYYY-MM-DD)": "2026-06-01",
  "Status (ACTIVE/INACTIVE)": "ACTIVE",
  "School Fees (blank = auto from fee structure)": "",
  Discount: "0",
};
